# Both covariance fields are omitted. Omission is unknown covariance.
header {
  sequence: 1
  source_time {
    seconds: 1700000000
    nanos: 250000000
  }
  receive_time {
    seconds: 1700000001
  }
  source_id: "eskf"
  frame_id: "world_enu"
  clock_domain: "monotonic"
  validity {
    state: STATE_VALID
  }
}
pose_world_from_body {
  position {
    x: 1
    y: 2
    z: -3
  }
  orientation {
    w: 1
  }
}
body_twist {
  linear_x_m_s: 0.5
}
mode: NAVIGATION_MODE_DEAD_RECKONING
estimator_epoch: 1
